config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :places, only: %i[new create destroy show index] do # edit update index
    resources :menu_items, only: %i[new create]
  end

  resources :menu_items, only: %i[destroy show index] # edit update

  root to: "pages#home"

  get "dashboard", to: "pages#dashboard"
  get "search", to: "pages#search", as: :search
  get "profile", to: "pages#profile"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  include PgSearch::Model
  multisearchable against: [:category, :name, :description]

  belongs_to :place
  has_one_attached :photo
  has_one :user, through: :place

  validates :name, :description, :visit_date, presence: true

  pg_search_scope :global_search,
  against: [:category, :name, :description],
  associated_against: {
    place: [:category, :name, :address, :cuisine]
  },
  using: {
    tsearch: { prefix: true }
  }
end

app/models/place.rb
class Place < ApplicationRecord
  include PgSearch::Model

  belongs_to :user
  has_many :menu_items, dependent: :destroy

  validates :name, presence: true

  # change the search methods ... watch the video!!

  pg_search_scope :search_category_name_address_cuisine,
  against: [:category, :name, :address, :cuisine],
  using: {
    tsearch: { prefix: true }
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :places
  has_many :menu_items, through: :places

  # validates :first_name, :email, :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  before_action :set_place, only: [:new, :create]
  def show
    @menu_item = MenuItem.find(params[:id])
  end

  def index
    @menu_items = current_user.menu_items
  end

  def new
    @menu_item = MenuItem.new
  end

  def create
    @menu_item = MenuItem.new(menu_params)
    @menu_item.place = @place
    if @menu_item.save
      redirect_to menu_item_path(@menu_item)
      flash.now[:success] = "The menu item has been created"
    else
      render :new, status: :unprocessable_entity
      flash.now[:error] = "Your data is not saved. Please provide valid data and try again."
    end
  end

  def destroy
    @menu_item = MenuItem.find(params[:id])
    @menu_item.destroy
    redirect_to dashboard_path  # needs to be directed to dashboard page
    flash.now[:success] = "The menu item has been deleted"
  end

  private

  def set_place
    @place = Place.find(params[:place_id])
  end

  def menu_params
    params.require(:menu_item).permit(:category, :name, :price, :visit_date, :rating, :description, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @no_navbar = true
  end

  def dashboard
    @places = current_user.places.last(5)
    @menu_items = current_user.menu_items
  end

  def search
    if params[:query].present?
      @places = Place.search_category_name_address_cuisine(params[:query])
      if @places.empty?
        flash.now[:notice] = "No results found for '#{params[:query]}'!"
      end
    else
      @places = Place.all
    end
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!

  def index
    @places = current_user.places
  end

  def new
    @place = Place.new
  end

  def create
    @place = Place.new(place_params)
    @place.user = current_user
    if @place.save
      redirect_to place_path(@place)
      flash.now[:success] = "The Place has been created"
    else
      flash.now[:error] = "Your data is not saved. Please provide valid data and try again."
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @place = Place.find(params[:id])
    @menu_items = @place.menu_items
  end

  def destroy
    @place = Place.find(params[:id])
    @place.destroy
    redirect_to places_path
  end

  private

  def place_params
    params.require(:place).permit(:name, :address, :cuisine, :category)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Historant</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
    <%= render 'shared/ios_pwa_links' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <% unless @no_navbar %>
      <%= render "shared/navbar" %>
    <% end %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>

    <% unless @no_navbar %>
    <% end %>
  </body>
</html>

app/views/menu_items/index.html.erb
<div class="container">
  <div class="row row-cols-1 row-cols-md-3 g-4">
    <% @menu_items.each do |menu_item| %>
      <div class="col">
        <%= link_to menu_item_path(menu_item) do %>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
            <%= menu_item.name %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/menu_items/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-xs-12 col-sm-4 col-sm-offset-4">
      <div class="form-login">
        <h2>Add a menu item </h2>
        <%= form_with([@place, @menu_item]) do |f| %>
          <div class="form-inputs">
            <%= f.input :name, class: 'form-control' %>
            <%= f.input :category, class: 'form-control' %>
            <%= f.input :price, class: 'form-control' %>
            <%= f.input :visit_date, class: 'form-control' %>
            <%= f.input :rating, class: 'form-control' %>
            <%= f.input :description, class: 'form-control' %>
            <%= f.input :photo, as: :file, class: 'form-control' %>
          </div>
          <div class="form-actions">
            <%= f.button :submit, "Create a menu item", class: "btn btn-ghost" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/menu_items/show.html.erb
<div class="container">
  <div class="card-showpage mb-4">
    <%= cl_image_tag @menu_item.photo.key%>

    <div class="card-showpage-infos">
      <h2><%= @menu_item.name %></h2>
      <p><em>from &nbsp<%=@menu_item.place.name %></em></p>
    </div>

    <div class="row card-showpage-infos">
      <div class= "col-6">
        <p><strong>Category:</strong></p>
        <p><em><%= @menu_item.category %></em></p>
      </div>
      <div class= "col-6">
        <p><strong>visited on:</strong></p>
        <p><em><%= @menu_item.visit_date.strftime("%A, %b %d") %></em></p>
      </div>
    </div>

    <div class="row card-showpage-infos">
      <div class= "col-6">
        <p><strong>Rating:</strong></p>
        <p>
          <% @menu_item.rating.times do %>
            <i class="fa-solid fa-star"></i>
          <% end %>
          <% (5 - @menu_item.rating).times do %>
            <i class="fa-regular fa-star"></i>
          <% end %>
        </p>
      </div>
      <div class= "col-6">
        <p><strong>Price:</strong></p>
        <p><em><%= @menu_item.price %>€</em></p>
      </div>
    </div>
    <div class="card-review">
      <p><strong>Review:</strong></p>
      <p><em><%= @menu_item.description %></em></p>
    </div>
  </div>
  <a href="/dashboard" class="btn btn-ghost" role="button">Go to dashboard</a>
</div>

app/views/pages/dashboard.html.erb
<div class="container">
  <h1>Dashboard</h1>
  <h2>Places you have visited</h2>

  <div id="places-carousel" class="carousel slide" data-bs-ride="carousel">
    <ol class="carousel-indicators">
      <% @places.each_with_index do |place, index| %>
        <li data-bs-target="#places-carousel" data-bs-slide-to="<%= index %>" class="<%= 'active' if index == 0 %>"></li>
      <% end %>
    </ol>
    <div class="carousel-inner">
      <% @places.each_with_index do |place, index| %>
        <div class="carousel-item <%= 'active' if index == 0 %>">
          <% if !place.menu_items.empty? && place.menu_items.last.photo.attached? %>
            <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path place.menu_items.last.photo.key %>')">
              <%= place.name %>
            </div>

          <% else %>
            <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
              <%= place.name %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
    <a class="carousel-control-prev" href="#places-carousel" role="button" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </a>
    <a class="carousel-control-next" href="#places-carousel" role="button" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </a>
  </div>
    <div class="d-flex justify-content-end">
    <%= link_to "see all", places_path, style: "text-decoration: none; color: red; font-size: 12px;" %>
  </div>

  <ul class="list-group" data-places-target="list">
    <% @places.each do |place| %>
      <% if place.name == "1" %>
        <li class="list-group-item"><%= place.name %></li>
      <% else %>
        <li class="list-group-item" hidden><%= place.name %></li>
      <% end %>
    <% end %>
  </ul>


  <br>

  <h2>You Have Eaten</h2>
  <div id="menu_items-carousel" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <% @menu_items.each_with_index do |menu_item, index| %>
        <div class="carousel-item <%= 'active' if index == 0 %>">
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path menu_item.photo.key %>')">
            <%= menu_item.name %>
          </div>
        </div>
      <% end %>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#menu_items-carousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#menu_items-carousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</div>

<div class="d-flex justify-content-end" style="position: relative; right: 125px;">
  <%= link_to "see all", menu_items_path, style: "text-decoration: none; mx-15px; color: red; font-size: 12px;" %>
</div>
<ul class="list-group" data-menu_items-target="list">
    <% @menu_items.each do |menu_item| %>
      <% if menu_item.name == "1" %>
        <li class="list-group-item"><%= menu_item.name %></li>
      <% else %>
        <li class="list-group-item" hidden><%= menu_item.name %></li>
      <% end %>
    <% end %>
  </ul>

app/views/pages/home.html.erb
<div class="container">
  <div class="row">
    <div class="card mx-auto col-sm-6 mt-5 border-0 home">
      <strong><h1>Welcome to</h1></strong>
      <img src="https://res.cloudinary.com/dwrkiuiqa/image/upload/v1678205141/Historant-logo-BIG-LOGO_vhiqzm.png" width="200" class="card-img-top" alt="Logo">
      <div class="card-body text-center">
        <h3>Already a member? <%= link_to "Log in", user_session_path %> </h3>
        <h3>New to Historant? <%= link_to "Sign up", new_user_registration_path %></h3>
        <h3> <%= link_to "Sign out", destroy_user_session_path, data: {turbo_method: :delete} %> </h3>
      </div>
    </div>
  </div>
</div>

app/views/pages/profile.html.erb
<div class="container my-4 py-4">
  <div class="container-background">
    <h1>Your Profile</h1>
    <div class="col-lg-8">
      <div class="card mx-auto col-sm-6 mt-5 border-0">
        <div class="card-body">
          <div class="row">
            <div class="col-sm-3">
              <p class="mb-0">Email:</p>
            </div>
            <div class="col-sm-9">
              <p class="text-muted mb-0">user@admin.com</p>
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-sm-3">
              <p class="mb-0">Name:</p>
            </div>
            <div class="col-sm-9">
              <p class="text-muted mb-0">Patricia Lambertz</p>
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-sm-3">
              <p class="mb-0">Mobile:</p>
            </div>
            <div class="col-sm-9">
              <p class="text-muted mb-0">(+49) 765-4321</p>
            </div>
          </div>
        </div>
      </div>
</div>

app/views/pages/search.html.erb
<div class="container">
  <div class="search">
      <%= form_with url: search_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control me-3",
        placeholder: "Search a keyword ..."
      %>
      <%= submit_tag "Search", class: "btn-ghost" %>
    <% end %>

    <% if flash.now[:notice].present? %>
    <div class="alert alert-info mt-3">
        <%= flash.now[:notice] %>
      </div>
    <% end %>
  </div>

  <ul>
    <% @places.each do |place| %>
      <li><%= place.name %></li>
    <% end %>
  </ul>
</div>

app/views/places/index.html.erb
<div class="container just-">
  <div class="row row-cols-1 row-cols-md-3 g-4">
    <% @places.each do |place| %>
      <div class="col">
        <%= link_to place_path(place) do %>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
              <%= place.name %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/places/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-xs-12 col-sm-4 col-sm-offset-4">
      <div class="form-login">
        <h2>Add a place </h2>
        <%= simple_form_for(@place) do |f| %>
          <%= f.input :category, collection: %w[Bakery Bar Buffet Cafe Food\ Truck Patisserie Restaurant Other] %>
          <%= f.input :name %>
          <%= f.input :cuisine, collection: %w[American Chinese German Greek Indian Italian Mexican Oriental Spanish Japanese Thai Turkish Vietnamese Other]%>
          <%= f.input :address %>
          <%= f.submit "Add place", class: "btn btn-flat" %>
          <!-- [...] -->
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/places/show.html.erb
<div class="container">
  <div class="card mt-3 text-center">
    <h1><%= @place.name %></h1>
    <p><strong>Category: &nbsp</strong><%= @place.category %></p>
    <% if @place.category == "Restaurant" %>
      <p><strong>Cuisine: &nbsp</strong><%= @place.cuisine %></p>
    <% end  %>
    <p><strong>Address: &nbsp</strong><%= @place.address %></p>
  </div>

  <% if @place.menu_items.present? %>
    <% @place.menu_items.each do |menu_item| %>
      <div class="card mt-3 text-center">
      <h1><%= menu_item.name %></h1>
      <p><strong>Category: &nbsp</strong><%= menu_item.category %></p>
      <p><strong>Visited on: &nbsp</strong><%= menu_item.visit_date.strftime("%A, %b %d") %></p>
      <p><strong>Rating: &nbsp</strong><%= menu_item.rating %></p>
      </div>
    <% end %>
  <% else %>
  <div class="card">
    <p>You have not been to <%= @place.name %> yet!</p>
  </div>
  <% end %>
</div>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light d-flex sticky-top row justify-content-around">
  <div class="container-fluid">
    <!-- New -->
    <button class="navbar-icon btn fa-2x magnifier-icon flex-fill" type="button">
      <%= link_to "/" do %>
      <i class="fa-sharp fa-solid fa-plus text-white"></i>
      <% end %>
    </button>
    <!-- Search -->
    <button class="navbar-icon magnifier-icon btn fa-2x flex-fill" type="button">
      <%= link_to "/search" do %>
      <i class="fa-sharp fa-solid fa-magnifying-glass text-white"></i>
      <% end %>
    </button>
    <!-- Logo -->
    <%= link_to "/", class: "navbar-brand flex-fill justify-content-center" do %>
      <%= image_tag "https://res.cloudinary.com/dwrkiuiqa/image/upload/v1678439564/Historant-logo-BIG-LOGO-WHITE_huxdwd.png" %>
    <% end %>
    <!-- Menu -->
    <button class="navbar-icon navbar-toggler btn fa-2x flex-fill" id="navbar-button" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
      <span class="fa-sharp fa-solid fa-bars"></span>
    </button>
    <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasNavbarLabel"><strong>Menu</strong></h5>
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/profile">Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/dashboard">Dashboard</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/places">Places</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/menu_items">Menu Items</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-danger" href="/users/sign_out" data-turbo-method="delete" >Sign out</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>